application: asksheilla
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /gaetk/static
  static_dir: lib/appengine-toolkit/static

- url: /gaetk/.*
  script: lib/appengine-toolkit/gaetk/defaulthandlers.py

- url: /robots.txt
  script: lib/appengine-toolkit/gaetk/defaulthandlers.py

- url: /version.txt
  script: lib/appengine-toolkit/gaetk/defaulthandlers.py

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /media
  static_dir: media

- url: /_ah/login_required
  script: lib/appengine-toolkit/gaetk/login.py

- url: /logout
  script: lib/appengine-toolkit/gaetk/login.py

- url: /tasks/.*
  script: taskmaster2.py
  login: required

- url: .*
  script: taskmaster/views.py
  login: required

libraries:
- name: jinja2
  version: "2.6"
- name: setuptools
  version: "0.6c11"
- name: markupsafe
  version: "0.15"

